### ISSUE TITLE
Run-time error '91': Object variable or With block variable not set

### ISSUE THREAD

**Issue by Essina** [pyscripter/XLRisk#16] opened 2024-04-11 11:51 UTC
Hi, We have recently downloaded and installed XLRISK. However, when we try to set up or configure, we get the subject error, please see screenshot below.
![Screenshot 2024-04-11 124746](https://github.com/pyscripter/XLRisk/assets/83407478/db128723-71e1-42ac-a4d4-40f971f0db55)

When I click on debug we get the following VBA code which I am not sure what to change from:
![Screenshot 2024-04-11 125040](https://github.com/pyscripter/XLRisk/assets/83407478/303d2090-7325-4f16-81cb-5f696d81a43d)

Will be grateful for your guidance.

Many thanks.

**Comment by pyscripter** [comment] 2024-04-11 12:24
Which Excel version are you using?

**Comment by pyscripter** [comment] 2024-04-11 12:43
Duplicate of https://github.com/pyscripter/XLRisk/issues/14

**Comment by Essina** [comment] 2024-04-11 12:46
MS365

**Comment by Essina** [comment] 2024-04-11 15:17
I closed Excel and restarted it so this worked as I can XLRisk Options Dialog. Thanks, I will go through the documentation and will reach out if I have other issues.

**Closed** 2024-04-12 09:25 UTC
Labels: duplicate
