### ISSUE TITLE
Excel crashes when running some simulations

### ISSUE THREAD

**Issue by dwschaffner** [pyscripter/XLRisk#3] opened 2022-01-29 15:59 UTC
Attached are copies of the crash report and the excel file.
[crash report.txt](https://github.com/pyscripter/XLRisk/files/7964040/crash.report.txt)
[Scenario 2 new.xlsx](https://github.com/pyscripter/XLRisk/files/7964045/Scenario.2.new.xlsx)
.

**Comment by pyscripter** [comment] 2022-01-29 16:01
Which version of Excel are you using?

**Comment by dwschaffner** [comment] 2022-01-29 16:05
Microsoft® Excel for Mac
Version 16.48 (21041102)
License: Microsoft 365 Subscription

**Comment by pyscripter** [comment] 2022-01-29 16:05
Here it runs without problems.

**Comment by dwschaffner** [comment] 2022-01-29 16:07
OK, I will let you know if I figure out what's causing it.

**Comment by pyscripter** [comment] 2022-01-29 16:07
You can try running in a different machine to see whether it runs.

**Comment by pyscripter** [comment] 2023-10-20 01:13
I am closing it since there is no feedback and the issue cannot be reproduced.

**Closed by pyscripter** 2023-10-20 01:13 UTC
